### ISSUE TITLE
Callback error when deploying app

### ISSUE THREAD

**Issue by hbandukw** [UBC-MDS/DSCI-532_2024_1_TBtracker#42]
Hey all, I am currently seeing the following error when deploying the app:

<img width="1692" alt="callback_error" src="https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/assets/20444993/6513036a-302f-47bd-a91f-4be8d331e155">

Need to investigate!

**Comment by hbandukw** [comment]
```
(TBtracker) hinabandukwala@Hinas-MBP ~/Documents/MDS/DSCI-532_2024_1_TBtracker (main)
$ python app.py 
Dash is running on http://127.0.0.1:8000/

 * Serving Flask app 'app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8000
Press CTRL+C to quit
127.0.0.1 - - [06/Apr/2024 16:10:56] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2024 16:10:56] "GET /_dash-component-suites/dash/deps/react@16.v2_16_1m1710075452.14.0.min.js HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2024 16:10:56] "GET /_dash-component-suites/dash/deps/react-dom@16.v2_16_1m1710075452.14.0.min.js HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2024 16:10:57] "GET /_dash-component-suites/dash/deps/prop-types@15.v2_16_1m1710075452.8.1.min.js HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2024 16:10:57] "GET /_dash-component-suites/dash/dcc/dash_core_components.v2_13_1m1710075452.js HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2024 16:10:57] "GET /_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_16_1m1710075452.min.js HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2024 16:10:57] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2024 16:10:57] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2024 16:10:57] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2024 16:10:57] "GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1" 304 -
127.0.0.1 - - [06/Apr/2024 16:10:57] "GET /_dash-component-suites/dash_vega_components/async-Vega.js HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2024 16:10:57] "POST /_dash-update-component HTTP/1.1" 200 -
[2024-04-06 16:10:57,430] ERROR in app: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/hinabandukwala/miniconda3/envs/TBtracker/lib/python3.12/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hinabandukwala/miniconda3/envs/TBtracker/lib/python3.12/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hinabandukwala/miniconda3/envs/TBtracker/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hinabandukwala/miniconda3/envs/TBtracker/lib/python3.12/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hinabandukwala/miniconda3/envs/TBtracker/lib/python3.12/site-packages/dash/dash.py", line 1352, in dispatch
    ctx.run(
  File "/Users/hinabandukwala/miniconda3/envs/TBtracker/lib/python3.12/site-packages/dash/_callback.py", line 450, in add_context
    output_value = _invoke_callback(func, *func_args, **func_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hinabandukwala/miniconda3/envs/TBtracker/lib/python3.12/site-packages/dash/_callback.py", line 39, in _invoke_callback
    return func(*args, **kwargs)  # %% callback invoked %%
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hinabandukwala/Documents/MDS/DSCI-532_2024_1_TBtracker/src/app.py", line 105, in render_content
    if "selected_country" in data and data["selected_country"]:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
127.0.0.1 - - [06/Apr/2024 16:10:57] "POST /_dash-update-component HTTP/1.1" 500 -
127.0.0.1 - - [06/Apr/2024 16:10:57] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2024 16:10:57] "POST /_dash-update-component HTTP/1.1" 204 -
127.0.0.1 - - [06/Apr/2024 16:10:57] "POST /_dash-update-component HTTP/1.1" 204 -
```

**Comment by sean-m-mckay** [comment]
Doesn't seem to be an issue anymore, closing
